local opt = vim.opt
local b = vim.b

b.autoformat = false
opt.backup = false -- creates a backup file
opt.cmdheight = 1 -- more space in the neovim command line for displaying messages
opt.colorcolumn = "100" -- side column
opt.confirm = true -- confirm to save changes before exiting modified buffer
opt.cursorline = false -- highlight the current line
opt.expandtab = true -- use spaces instead of tabs
opt.foldcolumn = "0" -- disable foldcolumn
opt.foldenable = true
opt.foldlevel = 99 -- using ufo provider needs a large value
opt.foldlevelstart = 99
opt.hlsearch = true -- highlight all matches on previous search pattern
opt.ignorecase = true -- ignore case
opt.list = false -- show some invisible characters
opt.mouse = "a" -- enable mouse mode
opt.number = true -- print line number
opt.relativenumber = true -- relative number lines
opt.scrolloff = 4 -- lines of context
opt.shiftwidth = 4 -- number of spaces to use for each step of (auto)indent
opt.signcolumn = "yes" -- always show the signcolumn
opt.smartcase = true -- don't ignore case with capitals
opt.smartindent = true -- insert indents automatically
opt.softtabstop = 4 -- number of spaces tabs counts for while performing editing operations
opt.spelllang = { "en" } -- spellchecking languages
opt.swapfile = false -- creates a swapfile
opt.tabstop = 4 -- number of spaces tabs count for
opt.termguicolors = true -- true color support
opt.undodir = os.getenv("HOME") .. "/nvim-data/undodir"
opt.undofile = true
opt.undolevels = 10000
opt.updatetime = 200 -- decrease update time
opt.wrap = true -- enable line wrap
